function blockObject(title, content, bgColor, childBlockObjects) {
    this.title = title;
    this.content = content;
    this.bgColor = bgColor;
    

    //Array of children contained in here..
    this.childBlockObjects = childBlockObjects;
    
    //These fields are generated by the code in visualizer and injected back
    //into this node object. Don't change them!
    this.posX = 0;
    this.posY = 0;
    this.width = 100;
    this.height = 100;
    
}