function blockObject(title, content, statementType, childBlockObjects) {
    this.title = title;
    this.statementType = statementType;
    
    ///Satement type can be many things, like a function or an if statement...
    
    //Array of children contained in here..
    this.childBlockObjects = childBlockObjects;
    if (childBlockObjects == null) {
        this.childBlockObjects = [];
    }
    
    this.content = content;
    if (content == null) {
        this.content = [];
    }
    
    //These fields are generated by the code in visualizer and injected back
    //into this node object. Don't change them!
    this.posX = 0;
    this.posY = 0;
    this.width = 0;
    this.height = 0;   
}